// Code generated by gtb. DO NOT EDIT.

package decrypt

import (
	cobra "github.com/spf13/cobra"
	props "gitlab.com/phpboyscout/go-tool-base/pkg/props"
	setup "gitlab.com/phpboyscout/go-tool-base/pkg/setup"
)

type DecryptOptions struct {
	Certificate string
	Key         string
	Backend     string
	Output      string
}

func NewCmdDecrypt(props *props.Props) *setup.Command {
	opts := &DecryptOptions{}

	cmd := setup.Wrap("decrypt", &cobra.Command{
		Use:   "decrypt",
		Short: "Decrypt an OpenPGP message addressed to a KMS-backed certificate",
		Long:  "Decrypt an OpenPGP message addressed to a KMS-backed certificate",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			props.ErrorHandler.SetUsage(cmd.Usage)
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			return RunDecrypt(cmd.Context(), props, opts, args)
		},
	})

	cmd.Flags().StringVar(&opts.Certificate, "certificate", "", "Path to the recipient certificate, or '-' for stdin")
	cmd.Flags().StringVar(&opts.Key, "key", "", "Key service identifier for the encryption subkey")
	cmd.Flags().StringVar(&opts.Backend, "backend", "", "Key service backend to use")
	cmd.Flags().StringVar(&opts.Output, "output", "", "Write plaintext here instead of stdout")

	return cmd
}
