// Code generated by gtb. DO NOT EDIT.

package certificate

import (
	cobra "github.com/spf13/cobra"
	props "gitlab.com/phpboyscout/go-tool-base/pkg/props"
	setup "gitlab.com/phpboyscout/go-tool-base/pkg/setup"
)

type CertificateOptions struct {
	UserId         string
	CertifyKey     string
	EncryptKey     string
	Backend        string
	Created        string
	Armor          bool
	Output         string
	FollowSymlinks bool
}

func NewCmdCertificate(props *props.Props) *setup.Command {
	opts := &CertificateOptions{}

	cmd := setup.Wrap("certificate", &cobra.Command{
		Use:   "certificate",
		Short: "Assemble and emit an OpenPGP certificate backed by key-service keys",
		Long:  "Assemble and emit an OpenPGP certificate backed by key-service keys",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			props.ErrorHandler.SetUsage(cmd.Usage)
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			return RunCertificate(cmd.Context(), props, opts, args)
		},
	})

	cmd.Flags().StringVar(&opts.UserId, "user-id", "", "Identity to certify, as 'Name <email>'")
	cmd.Flags().StringVar(&opts.CertifyKey, "certify-key", "", "Key service identifier for the certification primary")
	cmd.Flags().StringVar(&opts.EncryptKey, "encrypt-key", "", "Key service identifier for the encryption subkey")
	cmd.Flags().StringVar(&opts.Backend, "backend", "", "Key service backend to use")
	cmd.Flags().StringVar(&opts.Created, "created", "", "Key creation time as RFC 3339; must not change between runs")
	cmd.Flags().BoolVar(&opts.Armor, "armor", false, "Emit ASCII armour instead of binary")
	cmd.Flags().StringVar(&opts.Output, "output", "", "Write the certificate here instead of stdout")
	cmd.Flags().BoolVar(&opts.FollowSymlinks, "follow-symlinks", false, "Write through a symbolic link named by --output instead of refusing it")

	return cmd
}
