// Originally generated by gtb, then customized to attach the sign/keys
// command tree from go/signing-cli. Kept hands-off from regeneration via
// .gtb/ignore (`gtb ignore add pkg/cmd/root/cmd.go`).

package root

import (
	"embed"
	afero "github.com/spf13/afero"
	gtbRoot "gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root"
	logger "gitlab.com/phpboyscout/go-tool-base/pkg/logger"
	props "gitlab.com/phpboyscout/go-tool-base/pkg/props"
	setup "gitlab.com/phpboyscout/go-tool-base/pkg/setup"
	version "gitlab.com/phpboyscout/go-tool-base/pkg/version"
	errorhandling "gitlab.com/phpboyscout/go/errorhandling"
	signingcli "gitlab.com/phpboyscout/go/signing-cli"
	"os"
)

//go:embed assets/*
var assets embed.FS

func NewCmdRoot(v version.Info) (*setup.Command, *props.Props) {
	l := logger.NewCharm(os.Stderr, logger.WithTimestamp(true), logger.WithLevel(logger.InfoLevel))

	p := &props.Props{
		Assets: props.NewAssets(props.AssetMap{"root": &assets}),
		FS:     afero.NewOsFs(),
		Logger: l,
		Tool: props.Tool{
			Description: "Standalone artefact signing and verification CLI for the phpboyscout ecosystem",
			Features:    props.SetFeatures(props.Disable(props.McpCmd), props.Enable(props.ConfigCmd)),
			Name:        "sigillum",
			ReleaseSource: props.ReleaseSource{
				Host:  "gitlab.com",
				Owner: "phpboyscout",
				Repo:  "sigillum",
				Type:  "gitlab",
			},
			Summary: "sigillum utility",
		},
		Version: v,
	}

	p.ErrorHandler = errorhandling.New(logger.ToSlog(l), p.Tool.Help)

	// sigillum's raison d'être: the sign/keys command tree, sourced from
	// go/signing-cli (all real logic in go/signing). Attached as top-level
	// commands so `sigillum sign` / `sigillum keys ...` work directly.
	rootCmd := gtbRoot.NewCmdRoot(p,
		setup.Wrap("", signingcli.NewCmdSign(p.GetLogger())),
		setup.Wrap("", signingcli.NewCmdKeys(p.GetLogger())),
	)

	return rootCmd, p
}
