// Code generated by gtb. DO NOT EDIT.

package root

//go:generate go tool docs --project-root ../../.. --target-dir pkg/cmd/root/assets
//go:generate go tool changelog generate --output assets/CHANGELOG.md
