// Code generated by gtb. DO NOT EDIT.
//
// Generation provenance not present elsewhere in the generated source, so
// `gtb regenerate manifest` can reconstruct it from scratch. No runtime effect.
//
// gtb:signing enabled=true key_source=embedded backend=aws-kms key_id=alias%2Fgtb-release-signing-v2 kms_region=eu-west-2 public_key=internal%2Ftrustkeys%2Fkeys%2Fsigning-key-v2.asc

package root
