// Code generated by gtb. DO NOT EDIT.

// Self-update signature-verification enforcement defaults.
// Generated from the .gtb/manifest.yaml signing block; tune the
// posture via `gtb enable signing` flags, never by editing this file.
package root

import verify "gitlab.com/phpboyscout/go/signing/verify"

func init() {
	verify.DefaultKeySource = "embedded"
}
