// Code generated by gtb. DO NOT EDIT.

// Registers the forge adapters this tool ships, one module per line.
// Generated from the forge features in .gtb/manifest.yaml; enable or
// disable a forge and regenerate rather than editing this file.
package main

import (
	props "gitlab.com/phpboyscout/go-tool-base/pkg/props"
	_ "gitlab.com/phpboyscout/go/forge-gitlab"
)

func init() {
	props.DeclareLinks(props.ForgeLinkPrefix, "gitlab")
}
