// Code generated by gtb. DO NOT EDIT.

// Activates OS keychain support by blank-importing
// the go-keyring-backed Backend. Delete this file to
// ship a regulated build whose linked binary carries
// no session-bus / keychain IPC code. See
// docs/how-to/configure-credentials.md in the GTB repo.
package main

import _ "gitlab.com/phpboyscout/go/credentials/keychain"
