// Code generated by gtb. DO NOT EDIT.

// Links the keychain feature by blank-importing the framework
// package that declares it and contributes what it needs. The
// file is the switch: toggle it with `gtb enable keychain` /
// `gtb disable keychain`, and a build without this file carries
// nothing the package reaches.
package main

import _ "gitlab.com/phpboyscout/go-tool-base/pkg/setup/keychain"
