// Code generated by gtb. DO NOT EDIT.

package main

import (
	gtbRoot "gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root"
	version "gitlab.com/phpboyscout/sigillum/internal/version"
	root "gitlab.com/phpboyscout/sigillum/pkg/cmd/root"
)

// main delegates to gtbRoot.Execute, which runs the command tree with a
// signal-aware context: SIGINT/SIGTERM cancel cmd.Context() for graceful
// shutdown, a second signal force-exits immediately, and a signal-terminated
// run exits 128+signum (130 SIGINT, 143 SIGTERM).
func main() {
	rootCmd, p := root.NewCmdRoot(version.Get())
	gtbRoot.Execute(rootCmd, p)
}
