// Originally generated by gtb, then customized to attach the sign/keys command
// tree from go/signing-cli. Kept hands-off from regeneration via .gtb/ignore.
//
// This entrypoint is the deliberate home for custom command attachment: it has
// very low churn (it only ever calls NewCmdRoot + Execute), so holding it
// hands-off costs almost nothing — unlike the root command
// (pkg/cmd/root/cmd.go), which re-renders on every feature/command change and
// is better left generator-managed. See the go-tool-base feature request on a
// safe custom-command-attachment mechanism.

package main

import (
	"github.com/spf13/cobra"

	gtbRoot "gitlab.com/phpboyscout/go-tool-base/pkg/cmd/root"
	setup "gitlab.com/phpboyscout/go-tool-base/pkg/setup"
	signingcli "gitlab.com/phpboyscout/go/signing-cli"

	version "gitlab.com/phpboyscout/sigillum/internal/version"
	root "gitlab.com/phpboyscout/sigillum/pkg/cmd/root"
)

// main delegates to gtbRoot.Execute, which runs the command tree with a
// signal-aware context: SIGINT/SIGTERM cancel cmd.Context() for graceful
// shutdown, a second signal force-exits immediately, and a signal-terminated
// run exits 128+signum (130 SIGINT, 143 SIGTERM).
func main() {
	rootCmd, p := root.NewCmdRoot(version.Get())

	// sigillum's raison d'être: attach the sign/keys command tree from
	// go/signing-cli as top-level commands (all real logic in go/signing).
	// Attached here — not in the generated root — so `gtb enable signing` and
	// other root re-renders never drop it.
	rootCmd.Register(
		setup.Wrap("", skipConfig(signingcli.NewCmdSign(p.GetLogger()))),
		setup.Wrap("", skipConfig(signingcli.NewCmdKeys(p.GetLogger()))),
	)

	gtbRoot.Execute(rootCmd, p)
}

// skipConfig stamps cmd and every descendant so the root bootstrap relaxes its
// missing-config gate for them. The signing commands take all input via flags
// and a backend — they never need a config file — but sigillum enables the
// `init` feature, which otherwise makes config mandatory and breaks the
// release-CI signing step (`go run ./cmd/sigillum sign ...`, no config present).
func skipConfig(cmd *cobra.Command) *cobra.Command {
	setup.SkipConfigCheck(cmd)

	for _, sub := range cmd.Commands() {
		skipConfig(sub)
	}

	return cmd
}
